"""Sacramento museums data — hours, prices, links, map coordinates."""

# Google Maps search link covering all Sacramento museums
MAPS_LINK = "https://www.google.com/maps/search/museums+in+Sacramento+CA"

MUSEUMS = [
    {
        "name": "Crocker Art Museum",
        "emoji": "🎨",
        "category": "Art",
        "color": "#9C27B0",
        "description": "The oldest public art museum in the American West, featuring Californian, European, and Asian art across a landmark Victorian building and modern expansion.",
        "address": "216 O St, Sacramento, CA 95814",
        "website": "https://www.crockerart.org",
        "map": "https://maps.google.com/?q=Crocker+Art+Museum+Sacramento",
        "hours": [
            ("Tuesday–Friday", "10 AM – 5 PM"),
            ("Thursday", "10 AM – 9 PM"),
            ("Saturday–Sunday", "10 AM – 5 PM"),
            ("Monday", "Closed"),
        ],
        "admission": [
            ("Adults", "$15"),
            ("Seniors (65+)", "$12"),
            ("Students (w/ ID)", "$10"),
            ("Children under 7", "Free"),
            ("Members", "Free"),
        ],
        "free_note": "Free every Sunday 10 AM–1 PM",
        "highlights": ["19th-century California art", "German masters collection", "Works by Wayne Thiebaud"],
    },
    {
        "name": "California State Railroad Museum",
        "emoji": "🚂",
        "category": "History",
        "color": "#795548",
        "description": "One of the finest railroad museums in North America, with 21 restored locomotives and cars spanning the 1860s transcontinental railroad era through the 20th century.",
        "address": "125 I St, Sacramento, CA 95814",
        "website": "https://www.californiastaterailroadmuseum.org",
        "map": "https://maps.google.com/?q=California+State+Railroad+Museum+Sacramento",
        "hours": [
            ("Daily", "10 AM – 5 PM"),
        ],
        "admission": [
            ("Adults", "$12"),
            ("Youth (6–17)", "$6"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["21 restored locomotives", "Steam train rides (seasonal)", "Gold Rush-era history"],
    },
    {
        "name": "Sacramento History Museum",
        "emoji": "🏛️",
        "category": "History",
        "color": "#795548",
        "description": "Located in Old Sacramento's replica 1854 City Hall, the museum chronicles Sacramento's transformation from Gold Rush boomtown to California's capital city.",
        "address": "101 I St, Sacramento, CA 95814",
        "website": "https://www.sachistorymuseum.org",
        "map": "https://maps.google.com/?q=Sacramento+History+Museum",
        "hours": [
            ("Daily", "10 AM – 5 PM"),
        ],
        "admission": [
            ("Adults", "$10"),
            ("Seniors / Students", "$8"),
            ("Children (6–17)", "$5"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["Gold Rush artifacts", "Original city documents", "Underground Sacramento tours"],
    },
    {
        "name": "California Museum",
        "emoji": "🐻",
        "category": "History & Culture",
        "color": "#d4a017",
        "description": "California's official museum, celebrating the stories, people, and innovations that define the Golden State — from Native California to modern cultural icons.",
        "address": "1020 O St, Sacramento, CA 95814",
        "website": "https://www.californiamuseum.org",
        "map": "https://maps.google.com/?q=California+Museum+Sacramento",
        "hours": [
            ("Tuesday–Saturday", "10 AM – 5 PM"),
            ("Sunday", "12 PM – 5 PM"),
            ("Monday", "Closed"),
        ],
        "admission": [
            ("Adults", "$12"),
            ("Seniors (60+)", "$9"),
            ("Youth (6–13)", "$8"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["California Hall of Fame", "Native Californians exhibit", "Women's suffrage gallery"],
    },
    {
        "name": "Sutter's Fort State Historic Park",
        "emoji": "⚔️",
        "category": "Historic Site",
        "color": "#FF5722",
        "description": "The oldest restored fort in the American West and the first non-indigenous settlement in the Central Valley, founded by John Sutter in 1839 — a key Gold Rush landmark.",
        "address": "2701 L St, Sacramento, CA 95816",
        "website": "https://www.parks.ca.gov/?page_id=485",
        "map": "https://maps.google.com/?q=Sutter%27s+Fort+State+Historic+Park+Sacramento",
        "hours": [
            ("Daily", "10 AM – 5 PM"),
        ],
        "admission": [
            ("Adults", "$7"),
            ("Youth (6–17)", "$3"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["Restored 1840s buildings", "Living history demonstrations", "Gold Rush artifacts"],
    },
    {
        "name": "Governor's Mansion State Historic Park",
        "emoji": "🏡",
        "category": "Historic Site",
        "color": "#3F51B5",
        "description": "An elegant 1877 Victorian mansion that served as home to 13 California governors from 1903 to 1967, furnished with original Victorian antiques and artifacts.",
        "address": "1526 H St, Sacramento, CA 95814",
        "website": "https://www.parks.ca.gov/?page_id=486",
        "map": "https://maps.google.com/?q=Governor%27s+Mansion+State+Historic+Park+Sacramento",
        "hours": [
            ("Saturday–Sunday", "10 AM – 5 PM (tours on the hour)"),
            ("Monday–Friday", "Closed"),
        ],
        "admission": [
            ("Adults", "$7"),
            ("Youth (6–17)", "$3"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["13 governors' furnishings", "Victorian architecture", "Guided mansion tours"],
    },
    {
        "name": "California State Capitol Museum",
        "emoji": "🏛️",
        "category": "Historic Site",
        "color": "#d4a017",
        "description": "Explore the restored legislative chambers of the 1869 California State Capitol, including the original Governor's Office and restored 19th-century assembly and senate rooms.",
        "address": "1315 10th St, Sacramento, CA 95814",
        "website": "https://capitolmuseum.ca.gov",
        "map": "https://maps.google.com/?q=California+State+Capitol+Museum+Sacramento",
        "hours": [
            ("Daily", "9 AM – 5 PM"),
        ],
        "admission": [
            ("All visitors", "Free"),
        ],
        "free_note": "Always free admission",
        "highlights": ["Restored 1906 legislature chambers", "Self-guided tours", "Capitol Park gardens"],
    },
    {
        "name": "California Automobile Museum",
        "emoji": "🚗",
        "category": "Transportation",
        "color": "#F44336",
        "description": "Over 150 historic vehicles from the dawn of the automobile age to modern classics, celebrating California car culture from 1885 to the present day.",
        "address": "2200 Front St, Sacramento, CA 95818",
        "website": "https://www.calautomuseum.org",
        "map": "https://maps.google.com/?q=California+Automobile+Museum+Sacramento",
        "hours": [
            ("Monday–Sunday", "10 AM – 5 PM"),
        ],
        "admission": [
            ("Adults", "$12"),
            ("Seniors (60+)", "$10"),
            ("Youth (5–17)", "$7"),
            ("Children under 5", "Free"),
        ],
        "free_note": "Free first Sunday of each month",
        "highlights": ["1885–present vehicles", "Rare California customs", "Rotating special exhibitions"],
    },
    {
        "name": "Sacramento Children's Museum",
        "emoji": "🎪",
        "category": "Children",
        "color": "#009688",
        "description": "Hands-on interactive exhibits designed for children 8 and under, with themed play zones covering science, culture, health, and creativity.",
        "address": "2701 Prospect Park Dr, Rancho Cordova, CA 95670",
        "website": "https://www.sackids.org",
        "map": "https://maps.google.com/?q=Sacramento+Children%27s+Museum",
        "hours": [
            ("Tuesday–Sunday", "9 AM – 4:30 PM"),
            ("Monday", "Closed"),
        ],
        "admission": [
            ("Children & Adults", "$11"),
            ("Under 1 year", "Free"),
        ],
        "free_note": None,
        "highlights": ["Tot Spot for under 2s", "Pretend play zones", "Rotating STEM exhibits"],
    },
    {
        "name": "Wells Fargo History Museum",
        "emoji": "🏦",
        "category": "History",
        "color": "#d4a017",
        "description": "Free museum inside the Wells Fargo Center featuring original Gold Rush artifacts, a genuine 19th-century Concord stagecoach, and the story of California banking history.",
        "address": "400 Capitol Mall, Sacramento, CA 95814",
        "website": "https://www.wellsfargohistory.com/museums/sacramento/",
        "map": "https://maps.google.com/?q=Wells+Fargo+History+Museum+Sacramento",
        "hours": [
            ("Monday–Friday", "9 AM – 5 PM"),
            ("Saturday–Sunday", "Closed"),
        ],
        "admission": [
            ("All visitors", "Free"),
        ],
        "free_note": "Always free admission",
        "highlights": ["Original Concord stagecoach", "Gold Rush nuggets & scales", "Telegraph artifacts"],
    },
    {
        "name": "Sacramento Science Center & Air Museum",
        "emoji": "✈️",
        "category": "Science",
        "color": "#2196F3",
        "description": "Military aviation artifacts and science exhibits at McClellan Air Force Base, featuring vintage aircraft from WWII to the Cold War era and hands-on science displays.",
        "address": "3200 Freedom Park Dr, McClellan, CA 95652",
        "website": "https://www.sacsciencecenter.org",
        "map": "https://maps.google.com/?q=Sacramento+Air+Museum+McClellan",
        "hours": [
            ("Tuesday–Sunday", "9 AM – 4 PM"),
            ("Monday", "Closed"),
        ],
        "admission": [
            ("Adults", "$12"),
            ("Seniors / Military", "$10"),
            ("Youth (5–17)", "$8"),
            ("Children under 5", "Free"),
        ],
        "free_note": None,
        "highlights": ["WWII aircraft", "SR-71 Blackbird cockpit", "Cold War-era jets"],
    },
    {
        "name": "Leland Stanford Mansion State Historic Park",
        "emoji": "🏠",
        "category": "Historic Site",
        "color": "#795548",
        "description": "The restored 1856 mansion of railroad baron and California Governor Leland Stanford — a key figure in the Transcontinental Railroad and founder of Stanford University.",
        "address": "800 N St, Sacramento, CA 95814",
        "website": "https://www.parks.ca.gov/?page_id=487",
        "map": "https://maps.google.com/?q=Leland+Stanford+Mansion+Sacramento",
        "hours": [
            ("Thursday–Sunday", "10 AM – 4 PM (hourly tours)"),
            ("Monday–Wednesday", "Closed"),
        ],
        "admission": [
            ("Adults", "$7"),
            ("Youth (6–17)", "$3"),
            ("Children under 6", "Free"),
        ],
        "free_note": None,
        "highlights": ["Leland Stanford's personal artifacts", "Restored Victorian rooms", "Transcontinental Railroad history"],
    },
]
