"""
Sacramento restaurants grouped by cuisine.
Ratings sourced from Google Maps — subject to change.
Max 15 per cuisine group, ordered by rating desc.
"""

# Each restaurant:
#   name, rating, price ($ $$ $$$ $$$$), address, map_url, website, note (optional)

CUISINES = [
    {
        "id": "california",
        "label": "California / Farm-to-Fork",
        "emoji": "🌾",
        "color": "#4CAF50",
        "blurb": "Sacramento is America's Farm-to-Fork Capital. These restaurants showcase the region's extraordinary local produce, meats, and artisan products.",
        "restaurants": [
            {"name": "The Kitchen Restaurant", "rating": 4.7, "price": "$$$$", "address": "2225 Hurley Way, Sacramento", "map": "https://maps.google.com/?q=The+Kitchen+Restaurant+Sacramento", "website": "https://www.thekitchenrestaurant.com", "note": "James Beard Award-winning; prix-fixe only"},
            {"name": "Ella Dining Room & Bar", "rating": 4.5, "price": "$$$", "address": "1131 K St, Sacramento", "map": "https://maps.google.com/?q=Ella+Dining+Room+Bar+Sacramento", "website": "https://www.elladiningroom.com", "note": "Modern American in downtown"},
            {"name": "Mulvaney's Building & Loan", "rating": 4.5, "price": "$$$", "address": "1215 19th St, Sacramento", "map": "https://maps.google.com/?q=Mulvaney%27s+Building+%26+Loan+Sacramento", "website": "https://www.mulvaneysbl.com", "note": "Farm-to-fork pioneer"},
            {"name": "Waterboy Restaurant", "rating": 4.6, "price": "$$$", "address": "2000 Capitol Ave, Sacramento", "map": "https://maps.google.com/?q=Waterboy+Restaurant+Sacramento", "website": "https://www.waterboyrestaurant.com", "note": "French-California; outstanding wine list"},
            {"name": "Selland's Market-Cafe", "rating": 4.6, "price": "$$", "address": "5340 Elvas Ave, Sacramento", "map": "https://maps.google.com/?q=Selland%27s+Market+Cafe+Sacramento", "website": "https://sellands.com", "note": "Market cafe; great for lunch"},
            {"name": "Grange Restaurant & Bar", "rating": 4.3, "price": "$$$", "address": "926 J St, Sacramento", "map": "https://maps.google.com/?q=Grange+Restaurant+Bar+Sacramento", "website": "https://www.grangesacramento.com", "note": "Inside Citizen Hotel; seasonal menu"},
            {"name": "Paragary's", "rating": 4.3, "price": "$$$", "address": "1401 28th St, Sacramento", "map": "https://maps.google.com/?q=Paragary%27s+Sacramento", "website": "https://paragarys.com", "note": "Sacramento institution since 1983"},
            {"name": "Tower Cafe", "rating": 4.4, "price": "$$", "address": "1518 Broadway, Sacramento", "map": "https://maps.google.com/?q=Tower+Cafe+Sacramento", "website": "https://www.towercafe.com", "note": "Eclectic global menu; iconic landmark"},
            {"name": "Allspice Restaurant", "rating": 4.6, "price": "$$$", "address": "7111 Fair Oaks Blvd, Carmichael", "map": "https://maps.google.com/?q=Allspice+Restaurant+Carmichael", "website": "https://allspicerestaurant.com", "note": "Intimate farm-to-fork"},
            {"name": "Bacon & Butter", "rating": 4.4, "price": "$$", "address": "5913 Broadway, Sacramento", "map": "https://maps.google.com/?q=Bacon+%26+Butter+Sacramento", "website": "https://www.baconandbuttersac.com", "note": "Best brunch in Sacramento"},
        ],
    },
    {
        "id": "mexican",
        "label": "Mexican & Latin",
        "emoji": "🌮",
        "color": "#FF5722",
        "blurb": "Sacramento's large Latino community has cultivated an outstanding Mexican food scene, from street-style taquerias to elevated regional Mexican cuisine.",
        "restaurants": [
            {"name": "La Cosecha Bar + Restaurant", "rating": 4.5, "price": "$$$", "address": "1809 Capitol Ave, Sacramento", "map": "https://maps.google.com/?q=La+Cosecha+Sacramento", "website": "https://lacosechasacramento.com", "note": "Modern Latin; stunning cocktails"},
            {"name": "Taqueria El Buen Sabor", "rating": 4.6, "price": "$", "address": "4306 Mack Rd, Sacramento", "map": "https://maps.google.com/?q=Taqueria+El+Buen+Sabor+Sacramento", "website": None, "note": "Authentic & cash-only; best al pastor in the city"},
            {"name": "Tres Hermanas Restaurant", "rating": 4.4, "price": "$$", "address": "1128 R St, Sacramento", "map": "https://maps.google.com/?q=Tres+Hermanas+Sacramento", "website": "https://www.treshermanassac.com", "note": "Family-owned; homemade tortillas"},
            {"name": "Lalo's Mexican Restaurant", "rating": 4.5, "price": "$$", "address": "2812 16th St, Sacramento", "map": "https://maps.google.com/?q=Lalo%27s+Mexican+Restaurant+Sacramento", "website": None, "note": "Neighborhood favorite since the '90s"},
            {"name": "Chando's Tacos", "rating": 4.4, "price": "$", "address": "Multiple Sacramento locations", "map": "https://maps.google.com/?q=Chando%27s+Tacos+Sacramento", "website": "https://chandostacos.com", "note": "Sacramento taco institution"},
            {"name": "Centro Cocina Mexicana", "rating": 4.2, "price": "$$", "address": "2730 J St, Sacramento", "map": "https://maps.google.com/?q=Centro+Cocina+Mexicana+Sacramento", "website": "https://centrosacramento.com", "note": "Midtown staple with great margaritas"},
            {"name": "La Veracruzana", "rating": 4.5, "price": "$", "address": "1408 4th St, Sacramento", "map": "https://maps.google.com/?q=La+Veracruzana+Sacramento", "website": None, "note": "Old Sacramento; Veracruz-style seafood"},
            {"name": "Azul Mexican Restaurant", "rating": 4.3, "price": "$$", "address": "2326 Fair Oaks Blvd, Sacramento", "map": "https://maps.google.com/?q=Azul+Mexican+Restaurant+Sacramento", "website": None, "note": "Vibrant flavors and generous portions"},
            {"name": "Taco Loco", "rating": 4.4, "price": "$", "address": "2327 Arden Way, Sacramento", "map": "https://maps.google.com/?q=Taco+Loco+Sacramento", "website": None, "note": "Late-night tacos; family favorite"},
        ],
    },
    {
        "id": "japanese",
        "label": "Japanese & Ramen",
        "emoji": "🍣",
        "color": "#F44336",
        "blurb": "Sacramento's Japanese food scene ranges from acclaimed omakase sushi to deeply rich ramen broths and Japanese-American fusion.",
        "restaurants": [
            {"name": "Kru Contemporary Japanese", "rating": 4.5, "price": "$$$", "address": "3135 Folsom Blvd, Sacramento", "map": "https://maps.google.com/?q=Kru+Contemporary+Japanese+Sacramento", "website": "https://www.krurestaurant.com", "note": "Best omakase in Sacramento"},
            {"name": "Shoki Ramen House", "rating": 4.5, "price": "$$", "address": "2675 Del Paso Blvd, Sacramento", "map": "https://maps.google.com/?q=Shoki+Ramen+House+Sacramento", "website": "https://www.shokiramenhouse.com", "note": "Legendary broth; long waits worth it"},
            {"name": "Ryujin Ramen", "rating": 4.6, "price": "$$", "address": "2226 10th St, Sacramento", "map": "https://maps.google.com/?q=Ryujin+Ramen+Sacramento", "website": "https://www.ryujinramen.com", "note": "Rich tonkotsu; top-rated ramen spot"},
            {"name": "Mikuni Japanese Restaurant", "rating": 4.4, "price": "$$$", "address": "Multiple Sacramento locations", "map": "https://maps.google.com/?q=Mikuni+Japanese+Restaurant+Sacramento", "website": "https://www.mikunisushi.com", "note": "Sacramento sushi institution since 1987"},
            {"name": "Goldfish Japanese Food", "rating": 4.5, "price": "$$", "address": "2015 J St, Sacramento", "map": "https://maps.google.com/?q=Goldfish+Japanese+Food+Sacramento", "website": None, "note": "Casual hand rolls and izakaya"},
            {"name": "Aioli Bodega Española", "rating": 4.3, "price": "$$", "address": "1800 L St, Sacramento", "map": "https://maps.google.com/?q=Aioli+Bodega+Espa%C3%B1ola+Sacramento", "website": "https://aiolirestaurant.com", "note": "Spanish tapas; sake bar"},
            {"name": "Tora Restaurant", "rating": 4.4, "price": "$$", "address": "2730 J St, Sacramento", "map": "https://maps.google.com/?q=Tora+Restaurant+Sacramento", "website": None, "note": "Japanese comfort food; excellent gyoza"},
            {"name": "Sunh Fish", "rating": 4.5, "price": "$$", "address": "1800 Tribute Rd, Sacramento", "map": "https://maps.google.com/?q=Sunh+Fish+Sacramento", "website": None, "note": "Korean-Japanese fusion; popular lunch"},
        ],
    },
    {
        "id": "vietnamese",
        "label": "Vietnamese",
        "emoji": "🍜",
        "color": "#FF9800",
        "blurb": "Sacramento has one of the largest Vietnamese communities outside of Vietnam, centered around Little Saigon on Stockton Blvd — with some of the best pho in California.",
        "restaurants": [
            {"name": "Pho Bac Hoa Viet", "rating": 4.6, "price": "$", "address": "6040 Stockton Blvd, Sacramento", "map": "https://maps.google.com/?q=Pho+Bac+Hoa+Viet+Sacramento", "website": None, "note": "Legendary pho; Little Saigon landmark"},
            {"name": "Pho 777", "rating": 4.5, "price": "$", "address": "Multiple Sacramento locations", "map": "https://maps.google.com/?q=Pho+777+Sacramento", "website": None, "note": "Reliable pho chain with huge portions"},
            {"name": "Mom's Original Vietnamese", "rating": 4.6, "price": "$", "address": "6825 Stockton Blvd, Sacramento", "map": "https://maps.google.com/?q=Mom%27s+Original+Vietnamese+Sacramento", "website": None, "note": "Home-style cooking; banh mi standout"},
            {"name": "Viet Palace Restaurant", "rating": 4.4, "price": "$", "address": "6844 Stockton Blvd, Sacramento", "map": "https://maps.google.com/?q=Viet+Palace+Restaurant+Sacramento", "website": None, "note": "Large menu; great vermicelli bowls"},
            {"name": "Pho Saigon", "rating": 4.3, "price": "$", "address": "4240 Mack Rd, Sacramento", "map": "https://maps.google.com/?q=Pho+Saigon+Sacramento", "website": None, "note": "South Sacramento stalwart"},
            {"name": "Broderick Midtown", "rating": 4.2, "price": "$$", "address": "1800 L St, Sacramento", "map": "https://maps.google.com/?q=Broderick+Midtown+Sacramento", "website": None, "note": "Modern Vietnamese-American burgers"},
            {"name": "Tank House BBQ & Bar", "rating": 4.4, "price": "$$", "address": "1925 Del Paso Blvd, Sacramento", "map": "https://maps.google.com/?q=Tank+House+BBQ+Sacramento", "website": "https://tankhousebbq.com", "note": "Vietnamese-influenced BBQ fusion"},
            {"name": "Saigon Alley Kitchen & Bar", "rating": 4.4, "price": "$$", "address": "2001 K St, Sacramento", "map": "https://maps.google.com/?q=Saigon+Alley+Kitchen+Bar+Sacramento", "website": "https://saigonalleykitchen.com", "note": "Modern Vietnamese; great cocktails"},
            {"name": "Long Phuong Restaurant", "rating": 4.5, "price": "$", "address": "7809 Stockton Blvd, Sacramento", "map": "https://maps.google.com/?q=Long+Phuong+Restaurant+Sacramento", "website": None, "note": "Traditional Vietnamese; late hours"},
        ],
    },
    {
        "id": "chinese",
        "label": "Chinese",
        "emoji": "🥢",
        "color": "#F44336",
        "blurb": "From Cantonese dim sum to Sichuan hot pot, Sacramento's Chinese restaurant scene reflects the city's deep historic ties to Chinese immigrant communities dating to the Gold Rush.",
        "restaurants": [
            {"name": "Empress Tavern", "rating": 4.4, "price": "$$$", "address": "1013 K St, Sacramento", "map": "https://maps.google.com/?q=Empress+Tavern+Sacramento", "website": "https://empresstavern.com", "note": "Historic 1915 Chinese theater; elevated menu"},
            {"name": "Fat's Asia Bistro", "rating": 4.3, "price": "$$", "address": "806 15th St, Sacramento", "map": "https://maps.google.com/?q=Fat%27s+Asia+Bistro+Sacramento", "website": "https://fatsrestaurants.com", "note": "Sacramento chain; reliable dim sum"},
            {"name": "New Canton Restaurant", "rating": 4.4, "price": "$$", "address": "1507 Broadway, Sacramento", "map": "https://maps.google.com/?q=New+Canton+Restaurant+Sacramento", "website": None, "note": "Weekend dim sum destination"},
            {"name": "China Village", "rating": 4.5, "price": "$$", "address": "1335 Academy Dr, Sacramento", "map": "https://maps.google.com/?q=China+Village+Restaurant+Sacramento", "website": None, "note": "Peking duck done right"},
            {"name": "Chuan Restaurant", "rating": 4.5, "price": "$$", "address": "2425 16th St, Sacramento", "map": "https://maps.google.com/?q=Chuan+Restaurant+Sacramento", "website": None, "note": "Sichuan hot pot and spicy dishes"},
            {"name": "Sam's Hof Brau", "rating": 4.2, "price": "$$", "address": "2500 Watt Ave, Sacramento", "map": "https://maps.google.com/?q=Sam%27s+Hof+Brau+Sacramento", "website": None, "note": "Sacramento classic; cafeteria-style"},
            {"name": "Frank Fat's", "rating": 4.4, "price": "$$$", "address": "806 L St, Sacramento", "map": "https://maps.google.com/?q=Frank+Fat%27s+Sacramento", "website": "https://frankfats.com", "note": "1939 Sacramento political institution"},
            {"name": "Shanghai Garden", "rating": 4.3, "price": "$$", "address": "3345 Bradshaw Rd, Sacramento", "map": "https://maps.google.com/?q=Shanghai+Garden+Sacramento", "website": None, "note": "Authentic Shanghai-style dishes"},
        ],
    },
    {
        "id": "italian",
        "label": "Italian",
        "emoji": "🍝",
        "color": "#4CAF50",
        "blurb": "Sacramento's Italian community has deep roots, and the city boasts some of Northern California's finest trattorias, wood-fired pizza joints, and classic ristorantes.",
        "restaurants": [
            {"name": "Biba Restaurant", "rating": 4.5, "price": "$$$", "address": "2801 Capitol Ave, Sacramento", "map": "https://maps.google.com/?q=Biba+Restaurant+Sacramento", "website": "https://www.biba-restaurant.com", "note": "Bologna-born chef Biba Caggiano; Sacramento legend"},
            {"name": "Maranello Restaurant", "rating": 4.5, "price": "$$$", "address": "8928 N Lake Dr, Fair Oaks", "map": "https://maps.google.com/?q=Maranello+Restaurant+Fair+Oaks", "website": "https://www.maranellorestaurant.com", "note": "Ferrari-themed; exceptional pasta"},
            {"name": "Il Fornaio", "rating": 4.2, "price": "$$$", "address": "400 Capitol Mall, Sacramento", "map": "https://maps.google.com/?q=Il+Fornaio+Sacramento", "website": "https://www.ilfornaio.com", "note": "Upscale Italian in Capitol area"},
            {"name": "Piatti Ristorante", "rating": 4.3, "price": "$$$", "address": "571 Pavilions Ln, Sacramento", "map": "https://maps.google.com/?q=Piatti+Ristorante+Sacramento", "website": "https://www.piatti.com/sacramento/", "note": "Regional Italian; popular patio"},
            {"name": "Paesanos Ristorante", "rating": 4.4, "price": "$$", "address": "1806 Capitol Ave, Sacramento", "map": "https://maps.google.com/?q=Paesanos+Ristorante+Sacramento", "website": "https://paesanossac.com", "note": "Midtown neighborhood Italian"},
            {"name": "Pizza Rock", "rating": 4.4, "price": "$$", "address": "1020 K St, Sacramento", "map": "https://maps.google.com/?q=Pizza+Rock+Sacramento", "website": "https://pizzarocksacramento.com", "note": "Tony Gemignani's world-champion pizza"},
            {"name": "Amaro's Table", "rating": 4.5, "price": "$$$", "address": "401 I St, Sacramento", "map": "https://maps.google.com/?q=Amaro%27s+Table+Sacramento", "website": "https://amarostable.com", "note": "New Italian-American; Old Sacramento waterfront"},
            {"name": "Biba's Café", "rating": 4.3, "price": "$$", "address": "1820 L St, Sacramento", "map": "https://maps.google.com/?q=Biba%27s+Cafe+Sacramento", "website": None, "note": "Casual sibling to Biba Restaurant"},
            {"name": "La Trattoria Bohemia", "rating": 4.4, "price": "$$", "address": "3649 J St, Sacramento", "map": "https://maps.google.com/?q=La+Trattoria+Bohemia+Sacramento", "website": None, "note": "Czech-Italian fusion; unique Sacramento gem"},
        ],
    },
    {
        "id": "indian",
        "label": "Indian",
        "emoji": "🍛",
        "color": "#FF9800",
        "blurb": "Sacramento's Indian restaurant scene spans Northern and Southern Indian cuisine, from rich Punjabi curries to delicate dosas, serving one of Northern California's largest South Asian communities.",
        "restaurants": [
            {"name": "Taste of India", "rating": 4.5, "price": "$$", "address": "1900 16th St, Sacramento", "map": "https://maps.google.com/?q=Taste+of+India+Sacramento", "website": "https://www.tasteofindiasac.com", "note": "Sacramento's most beloved Indian restaurant"},
            {"name": "Sher-E-Punjab", "rating": 4.4, "price": "$$", "address": "721 Broadway, Sacramento", "map": "https://maps.google.com/?q=Sher-E-Punjab+Sacramento", "website": None, "note": "Authentic Punjabi; tandoor specialties"},
            {"name": "Bombay Bar & Grill", "rating": 4.2, "price": "$$", "address": "2620 Fair Oaks Blvd, Sacramento", "map": "https://maps.google.com/?q=Bombay+Bar+%26+Grill+Sacramento", "website": "https://bombaybargrill.com", "note": "Lively bar; live Bollywood music weekends"},
            {"name": "Mayura Indian Restaurant", "rating": 4.3, "price": "$$", "address": "4040 Manzanita Ave, Carmichael", "map": "https://maps.google.com/?q=Mayura+Indian+Restaurant+Carmichael", "website": None, "note": "South Indian specialty; excellent dosas"},
            {"name": "Kathmandu Kitchen", "rating": 4.4, "price": "$$", "address": "1300 Del Paso Blvd, Sacramento", "map": "https://maps.google.com/?q=Kathmandu+Kitchen+Sacramento", "website": None, "note": "Nepali-Indian; momos and curry"},
            {"name": "India Gate", "rating": 4.3, "price": "$$", "address": "1262 Howe Ave, Sacramento", "map": "https://maps.google.com/?q=India+Gate+Restaurant+Sacramento", "website": None, "note": "Long-standing favorite; lunch buffet"},
            {"name": "Punjab Indian Cuisine", "rating": 4.2, "price": "$$", "address": "1811 Broadway, Sacramento", "map": "https://maps.google.com/?q=Punjab+Indian+Cuisine+Sacramento", "website": None, "note": "Budget-friendly; hearty portions"},
            {"name": "Curry Station", "rating": 4.3, "price": "$$", "address": "2929 Florin Rd, Sacramento", "map": "https://maps.google.com/?q=Curry+Station+Sacramento", "website": None, "note": "South Sacramento staple; great biryani"},
        ],
    },
    {
        "id": "thai",
        "label": "Thai",
        "emoji": "🥭",
        "color": "#9C27B0",
        "blurb": "Sacramento's Thai restaurant scene is vibrant and authentic, with many family-run spots serving regional dishes that go well beyond the typical pad thai.",
        "restaurants": [
            {"name": "Lemongrass Restaurant", "rating": 4.5, "price": "$$", "address": "601 Munroe St, Sacramento", "map": "https://maps.google.com/?q=Lemongrass+Restaurant+Sacramento", "website": "https://lemongrasskitchen.com", "note": "Thai-Southeast Asian fusion; romantic setting"},
            {"name": "Siam Kitchen", "rating": 4.3, "price": "$", "address": "1830 L St, Sacramento", "map": "https://maps.google.com/?q=Siam+Kitchen+Sacramento", "website": None, "note": "Quick, cheap, and delicious; lunch favorite"},
            {"name": "Thai House", "rating": 4.3, "price": "$$", "address": "820 K St, Sacramento", "map": "https://maps.google.com/?q=Thai+House+Restaurant+Sacramento", "website": None, "note": "Midtown Thai; great lunch specials"},
            {"name": "Zen Sushi & Thai", "rating": 4.2, "price": "$$", "address": "1477 W El Camino Ave, Sacramento", "map": "https://maps.google.com/?q=Zen+Sushi+Thai+Sacramento", "website": None, "note": "Thai-Japanese combo; good value"},
            {"name": "Racha Cafe", "rating": 4.4, "price": "$$", "address": "2704 J St, Sacramento", "map": "https://maps.google.com/?q=Racha+Cafe+Sacramento", "website": "https://rachacafe.com", "note": "Midtown staple; late night-friendly"},
            {"name": "Chada Thai", "rating": 4.4, "price": "$$", "address": "3011 El Camino Ave, Sacramento", "map": "https://maps.google.com/?q=Chada+Thai+Sacramento", "website": None, "note": "North Sacramento; authentic recipes"},
            {"name": "Thai Basil Kitchen", "rating": 4.3, "price": "$", "address": "4626 Freeport Blvd, Sacramento", "map": "https://maps.google.com/?q=Thai+Basil+Kitchen+Sacramento", "website": None, "note": "South Sac; quick and affordable"},
        ],
    },
    {
        "id": "bbq",
        "label": "BBQ & Southern",
        "emoji": "🔥",
        "color": "#795548",
        "blurb": "Sacramento's BBQ scene blends Texas-style smoke with California ingredients, with several spots earning regional and national recognition.",
        "restaurants": [
            {"name": "Tank House BBQ & Bar", "rating": 4.5, "price": "$$", "address": "1925 Del Paso Blvd, Sacramento", "map": "https://maps.google.com/?q=Tank+House+BBQ+Bar+Sacramento", "website": "https://tankhousebbq.com", "note": "Best BBQ in Sac; oak-smoked brisket"},
            {"name": "Bad A$$ BBQ Smoke House", "rating": 4.4, "price": "$$", "address": "2616 Del Paso Blvd, Sacramento", "map": "https://maps.google.com/?q=Bad+Ass+BBQ+Sacramento", "website": None, "note": "Oak-smoked meats; huge portions"},
            {"name": "Sqirl Smoke", "rating": 4.3, "price": "$$", "address": "4440 Florin Rd, Sacramento", "map": "https://maps.google.com/?q=Sqirl+Smoke+Sacramento", "website": None, "note": "South Sacramento BBQ gem"},
            {"name": "Buckhorn Steakhouse", "rating": 4.5, "price": "$$$", "address": "101 Main St, Winters", "map": "https://maps.google.com/?q=Buckhorn+Steakhouse+Winters+CA", "website": "https://www.buckhornsteakhouse.com", "note": "Short drive; worth the trip"},
            {"name": "Big Daddy's BBQ", "rating": 4.3, "price": "$$", "address": "9012 Bruceville Rd, Elk Grove", "map": "https://maps.google.com/?q=Big+Daddy%27s+BBQ+Elk+Grove", "website": None, "note": "Sac metro area soul food BBQ"},
            {"name": "Knotty Pine Supper Club", "rating": 4.4, "price": "$$", "address": "4815 Auburn Blvd, Sacramento", "map": "https://maps.google.com/?q=Knotty+Pine+Supper+Club+Sacramento", "website": None, "note": "Old-school steakhouse and BBQ"},
            {"name": "Poke Sac", "rating": 4.3, "price": "$", "address": "5700 24th St, Sacramento", "map": "https://maps.google.com/?q=Poke+Sac+Sacramento", "website": None, "note": "Hawaiian BBQ fusion"},
        ],
    },
    {
        "id": "burgers",
        "label": "Burgers & American",
        "emoji": "🍔",
        "color": "#2196F3",
        "blurb": "From smash burgers to gourmet creations, Sacramento's burger scene has something for every appetite — including several nationally recognized spots.",
        "restaurants": [
            {"name": "Hoppy's On The Levee", "rating": 4.4, "price": "$$", "address": "2710 N Market St, Sacramento", "map": "https://maps.google.com/?q=Hoppy%27s+on+the+Levee+Sacramento", "website": "https://hoppybrewing.com", "note": "Craft beer + great pub food"},
            {"name": "Federalist Public House", "rating": 4.3, "price": "$$", "address": "1640 R St, Sacramento", "map": "https://maps.google.com/?q=Federalist+Public+House+Sacramento", "website": "https://federalistpublichouse.com", "note": "R Street; upscale pub burger"},
            {"name": "Squeeze Inn", "rating": 4.5, "price": "$", "address": "7918 Fruitridge Rd, Sacramento", "map": "https://maps.google.com/?q=Squeeze+Inn+Sacramento", "website": "https://www.squeezeinn.com", "note": "Famous cheese skirt burger; featured on Food Network"},
            {"name": "Hook & Ladder", "rating": 4.5, "price": "$$", "address": "1630 S St, Sacramento", "map": "https://maps.google.com/?q=Hook+%26+Ladder+Sacramento", "website": "https://hookandladdermanufacturing.com", "note": "Old fire station; excellent brunch burgers"},
            {"name": "The Golden Bear", "rating": 4.3, "price": "$$", "address": "1710 L St, Sacramento", "map": "https://maps.google.com/?q=The+Golden+Bear+Sacramento", "website": "https://thegoldenbear.com", "note": "Midtown bar; smash burger"},
            {"name": "Burgers & Brew", "rating": 4.4, "price": "$$", "address": "1409 R St, Sacramento", "map": "https://maps.google.com/?q=Burgers+%26+Brew+Sacramento", "website": "https://burgersandbrew.com", "note": "Local craft beer + house-ground burgers"},
            {"name": "Revolution Burger", "rating": 4.4, "price": "$$", "address": "4680 Natomas Blvd, Sacramento", "map": "https://maps.google.com/?q=Revolution+Burger+Sacramento", "website": None, "note": "Natomas; gourmet patties"},
            {"name": "Red Robin", "rating": 4.0, "price": "$$", "address": "Multiple Sacramento locations", "map": "https://maps.google.com/?q=Red+Robin+Sacramento", "website": "https://www.redrobin.com", "note": "Family chain; unlimited fries"},
            {"name": "Kupros Craft House", "rating": 4.3, "price": "$$", "address": "1217 21st St, Sacramento", "map": "https://maps.google.com/?q=Kupros+Craft+House+Sacramento", "website": "https://kuproscrafthouse.com", "note": "Bar burgers + huge craft beer list"},
        ],
    },
    {
        "id": "seafood",
        "label": "Seafood",
        "emoji": "🦞",
        "color": "#0097A7",
        "blurb": "Proximity to the Sacramento Delta, San Francisco Bay, and Pacific coastline means Sacramento restaurants have access to some of California's freshest seafood.",
        "restaurants": [
            {"name": "Scott's Seafood on the River", "rating": 4.4, "price": "$$$", "address": "4800 Riverside Blvd, Sacramento", "map": "https://maps.google.com/?q=Scott%27s+Seafood+on+the+River+Sacramento", "website": "https://scottsseafoodgrill.com", "note": "Riverside dining; oysters + Dungeness crab"},
            {"name": "Rio City Cafe", "rating": 4.2, "price": "$$$", "address": "1110 Front St, Sacramento", "map": "https://maps.google.com/?q=Rio+City+Cafe+Sacramento", "website": "https://www.riocitycafe.com", "note": "Old Sacramento waterfront; great views"},
            {"name": "The Waterfront Restaurant", "rating": 4.3, "price": "$$$", "address": "Crossroads Hotel, Sacramento", "map": "https://maps.google.com/?q=The+Waterfront+Restaurant+Sacramento", "website": None, "note": "River views; sustainable seafood"},
            {"name": "Hook & Ladder", "rating": 4.5, "price": "$$", "address": "1630 S St, Sacramento", "map": "https://maps.google.com/?q=Hook+%26+Ladder+Sacramento", "website": "https://hookandladdermanufacturing.com", "note": "Oysters on weekends; farm-to-fork"},
            {"name": "Crawdads on the River", "rating": 4.3, "price": "$$", "address": "1375 Garden Hwy, Sacramento", "map": "https://maps.google.com/?q=Crawdads+on+the+River+Sacramento", "website": "https://www.crawdadsontheriver.com", "note": "Delta crawfish & American seafood"},
            {"name": "Fish Face Poke Bar", "rating": 4.4, "price": "$$", "address": "1801 Capitol Ave, Sacramento", "map": "https://maps.google.com/?q=Fish+Face+Poke+Bar+Sacramento", "website": "https://fishfacepokebar.com", "note": "Build-your-own poke bowls"},
            {"name": "Goldfish Sushi & Sake Bar", "rating": 4.5, "price": "$$", "address": "2015 J St, Sacramento", "map": "https://maps.google.com/?q=Goldfish+Sushi+Sacramento", "website": None, "note": "Sushi-focused; excellent sake selection"},
            {"name": "Sunh Fish Restaurant", "rating": 4.5, "price": "$$", "address": "1800 Tribute Rd, Sacramento", "map": "https://maps.google.com/?q=Sunh+Fish+Restaurant+Sacramento", "website": None, "note": "Korean seafood fusion"},
        ],
    },
]

# Google Maps search link for all Sacramento restaurants
MAPS_LINK = "https://www.google.com/maps/search/best+restaurants+in+Sacramento+CA"
