"""Pool of Sacramento trivia facts and quiz questions."""

FACTS = [
    {
        "emoji": "🏛️",
        "category": "Capital City",
        "color": "#d4a017",
        "fact": "Sacramento has been California's state capital since 1854",
        "detail": "Before Sacramento, California's capital moved around — San Jose, Vallejo, and Benicia all served as capital before Sacramento was made permanent.",
    },
    {
        "emoji": "⛏️",
        "category": "Gold Rush",
        "color": "#2196F3",
        "fact": "The California Gold Rush of 1848 put Sacramento on the map",
        "detail": "Sacramento became the main supply hub for the 300,000+ miners who flooded California. John Sutter's Fort was the first non-indigenous settlement in the area, established in 1839.",
    },
    {
        "emoji": "🌳",
        "category": "Tree City",
        "color": "#4CAF50",
        "fact": "Sacramento is known as the 'City of Trees'",
        "detail": "Sacramento has one of the largest urban forests in the world, with over 1 million trees lining its streets — more canopy coverage per capita than Paris or London.",
    },
    {
        "emoji": "🚂",
        "category": "Transcontinental Railroad",
        "color": "#795548",
        "fact": "Sacramento was the western terminus of the First Transcontinental Railroad",
        "detail": "In 1863, Sacramento was chosen as the starting point for the Central Pacific Railroad. The railroad was completed in 1869, connecting the country coast to coast for the first time.",
    },
    {
        "emoji": "🌾",
        "category": "Farm to Fork Capital",
        "color": "#FF5722",
        "fact": "Sacramento is America's Farm-to-Fork Capital",
        "detail": "Located in the Sacramento Valley, the region produces over 300 crops. Within 150 miles, you can find more food diversity than almost anywhere else in the world.",
    },
    {
        "emoji": "🏀",
        "category": "Sacramento Kings",
        "color": "#9C27B0",
        "fact": "The Sacramento Kings are the NBA's oldest franchise in continuous operation",
        "detail": "Founded in 1923 as the Rochester Seagrams, the Kings moved to Sacramento in 1985. They play at the Golden 1 Center, one of the most technologically advanced arenas in the world.",
    },
    {
        "emoji": "🌊",
        "category": "River City",
        "color": "#2196F3",
        "fact": "Sacramento sits at the confluence of the Sacramento and American rivers",
        "detail": "The two rivers meet just west of downtown. Sacramento is one of the most flood-prone cities in America, protected by an extensive levee system built over 150 years.",
    },
    {
        "emoji": "☀️",
        "category": "Sunny City",
        "color": "#d4a017",
        "fact": "Sacramento averages 265 sunny days per year — sunnier than Miami",
        "detail": "Summers are hot and dry with temperatures regularly exceeding 100°F. The Mediterranean climate makes Sacramento one of the sunniest large cities in the United States.",
    },
    {
        "emoji": "🏘️",
        "category": "Victorian Architecture",
        "color": "#795548",
        "fact": "Sacramento's 'Poverty Ridge' has one of California's finest Victorian home collections",
        "detail": "The area around 16th and H Streets (nicknamed ironically for its wealthy residents) contains hundreds of beautifully preserved Victorian mansions from the 1800s.",
    },
    {
        "emoji": "🎭",
        "category": "Pony Express",
        "color": "#F44336",
        "fact": "Sacramento was the western terminus of the Pony Express",
        "detail": "From 1860 to 1861, the Pony Express delivered mail between Sacramento and St. Joseph, Missouri in just 10 days — made obsolete by the telegraph after only 18 months.",
    },
    {
        "emoji": "🌉",
        "category": "Tower Bridge",
        "color": "#3F51B5",
        "fact": "Sacramento's Tower Bridge is one of only four vertical-lift bridges in California",
        "detail": "Opened in 1935, the golden Tower Bridge connects Sacramento to West Sacramento. It lifts vertically to allow tall ships to pass through to the Port of Sacramento.",
    },
    {
        "emoji": "🍅",
        "category": "Tomato Capital",
        "color": "#FF5722",
        "fact": "The Sacramento Valley produces about 90% of the nation's processed tomatoes",
        "detail": "California grows more tomatoes than any other state, and the Sacramento Valley leads that production. The region also dominates in almonds, rice, and stone fruits.",
    },
    {
        "emoji": "🦆",
        "category": "Wildlife",
        "color": "#4CAF50",
        "fact": "The Sacramento Valley hosts one of the largest waterfowl migrations in North America",
        "detail": "Every winter, millions of ducks, geese, and shorebirds travel the Pacific Flyway through the Sacramento Valley. The region has some of the best bird watching in the country.",
    },
    {
        "emoji": "🍷",
        "category": "Wine Country",
        "color": "#9C27B0",
        "fact": "The Sacramento region has more American Viticultural Areas than Napa Valley",
        "detail": "The Sierra Foothills wine region surrounding Sacramento has over 100 wineries. El Dorado, Amador, and Calaveras counties are renowned for Zinfandel and Syrah.",
    },
    {
        "emoji": "🎰",
        "category": "Entertainment",
        "color": "#3F51B5",
        "fact": "Sacramento is home to Thunder Valley Casino, one of California's highest-grossing casinos",
        "detail": "Owned by the United Auburn Indian Community, Thunder Valley opened in 2003 and generates over $500 million annually — one of the top tribal casinos in California.",
    },
    {
        "emoji": "🎨",
        "category": "Arts",
        "color": "#9C27B0",
        "fact": "The Crocker Art Museum is the oldest public art museum in the American West",
        "detail": "Founded in 1885, the Crocker Art Museum houses an impressive collection of Californian, European, and Asian art. It was donated to the city by Judge Edwin Crocker.",
    },
    {
        "emoji": "🚀",
        "category": "Technology",
        "color": "#2196F3",
        "fact": "Sacramento is one of the fastest-growing tech hubs outside Silicon Valley",
        "detail": "With lower costs than the Bay Area and proximity to UC Davis, Sacramento has attracted major tech companies and startups. Apple, Google, and Intel all have operations nearby.",
    },
    {
        "emoji": "🌮",
        "category": "Food Scene",
        "color": "#FF5722",
        "fact": "Sacramento has more restaurants per capita than San Francisco",
        "detail": "The combination of fresh local produce, diverse immigrant communities, and a thriving food culture makes Sacramento one of the best eating cities in California.",
    },
    {
        "emoji": "⚽",
        "category": "Soccer",
        "color": "#4CAF50",
        "fact": "Sacramento Republic FC set an attendance world record for a USL match",
        "detail": "In 2014, Sacramento Republic FC drew over 11,000 fans to their home opener — a record for the United Soccer League. The club later became an MLS expansion team.",
    },
    {
        "emoji": "🏥",
        "category": "Healthcare",
        "color": "#009688",
        "fact": "UC Davis Medical Center in Sacramento is one of the top trauma centers on the West Coast",
        "detail": "The UC Davis Medical Center is the only Level 1 trauma center in the region serving a 33-county area. It's also home to the UC Davis Comprehensive Cancer Center.",
    },
    {
        "emoji": "🎸",
        "category": "Music",
        "color": "#2196F3",
        "fact": "Sacramento has produced major music acts including Tesla, Deftones, and Cake",
        "detail": "The Sacramento music scene punches above its weight. Deftones formed at Del Campo High School in the 1980s and went on to global fame with alternative metal.",
    },
    {
        "emoji": "🌁",
        "category": "Fog",
        "color": "#795548",
        "fact": "Sacramento's winter 'tule fog' is one of the thickest ground fogs in the world",
        "detail": "Tule fog forms in the Central Valley when cold, moist air settles near the ground. Visibility can drop to near zero — it's the leading cause of weather-related accidents in California.",
    },
    {
        "emoji": "📚",
        "category": "Education",
        "color": "#9C27B0",
        "fact": "Sacramento State was founded in 1947 and is the only university in the California State system named after a city",
        "detail": "California State University, Sacramento (Sac State) serves over 30,000 students and is a major economic driver for the region, contributing over $2 billion annually to the local economy.",
    },
    {
        "emoji": "🛤️",
        "category": "Historic Route",
        "color": "#F44336",
        "fact": "The historic Lincoln Highway, America's first transcontinental road, passed through Sacramento",
        "detail": "Established in 1913, the Lincoln Highway ran from New York to San Francisco. Its western section through Sacramento helped establish the city as a key transportation hub.",
    },
    {
        "emoji": "🌿",
        "category": "Parks",
        "color": "#4CAF50",
        "fact": "William Land Park has been a community gathering place since 1918",
        "detail": "The 160-acre William Land Park in south Sacramento includes a golf course, Funderland amusement park, Sacramento Zoo, and William Land Regional Park — all free or low-cost.",
    },
    {
        "emoji": "🏊",
        "category": "Waterways",
        "color": "#2196F3",
        "fact": "The Sacramento-San Joaquin Delta is the largest estuary on the West Coast",
        "detail": "The Delta, east of Sacramento, is a 1,100-mile maze of waterways covering 700,000 acres. It supplies drinking water to 25 million Californians and supports a massive agricultural industry.",
    },
    {
        "emoji": "🎪",
        "category": "State Fair",
        "color": "#d4a017",
        "fact": "The California State Fair has been held in Sacramento every year since 1854",
        "detail": "Cal Expo hosts the California State Fair each summer, drawing nearly 500,000 visitors. It's one of the largest state fairs in the US, featuring agriculture, entertainment, and food.",
    },
    {
        "emoji": "🏗️",
        "category": "Old Sacramento",
        "color": "#795548",
        "fact": "Old Sacramento is a 28-acre National Historic Landmark",
        "detail": "Old Sacramento preserves the look of the 1850s Gold Rush era with wooden sidewalks, brick buildings, and cobblestone streets along the Sacramento River waterfront.",
    },
]

QUIZ = [
    {
        "question": "What year did Sacramento become California's permanent state capital?",
        "options": ["1850", "1852", "1854", "1860"],
        "answer": 2,
        "explanation": "Sacramento became the permanent capital in 1854 after the legislature grew tired of moving between San Jose, Vallejo, and Benicia.",
    },
    {
        "question": "What nickname is Sacramento known by because of its trees?",
        "options": ["The Forest City", "The City of Trees", "The Green City", "The Emerald City"],
        "answer": 1,
        "explanation": "Sacramento's urban forest of over 1 million trees earns it the nickname 'City of Trees' — with more canopy per capita than most cities worldwide.",
    },
    {
        "question": "Which two rivers meet near downtown Sacramento?",
        "options": ["Sacramento and San Joaquin", "Sacramento and American", "American and Feather", "Sacramento and Bear"],
        "answer": 1,
        "explanation": "The Sacramento River and American River converge just west of downtown, making Sacramento a true River City.",
    },
    {
        "question": "What percentage of America's processed tomatoes come from the Sacramento Valley?",
        "options": ["50%", "70%", "90%", "40%"],
        "answer": 2,
        "explanation": "The Sacramento Valley produces about 90% of all processed tomatoes in the United States.",
    },
    {
        "question": "In what year was the Pony Express replaced by the telegraph?",
        "options": ["1858", "1860", "1861", "1865"],
        "answer": 2,
        "explanation": "The Pony Express ran from April 1860 to October 1861, when the transcontinental telegraph made it obsolete after just 18 months.",
    },
    {
        "question": "What is the oldest public art museum in the American West?",
        "options": ["San Francisco Museum of Modern Art", "Crocker Art Museum", "Oakland Museum", "Los Angeles County Museum"],
        "answer": 1,
        "explanation": "The Crocker Art Museum, founded in 1885 and donated to Sacramento by Judge Edwin Crocker, is the oldest public art museum in the western United States.",
    },
    {
        "question": "How many sunny days does Sacramento average per year?",
        "options": ["200", "230", "265", "290"],
        "answer": 2,
        "explanation": "Sacramento averages 265 sunny days per year — sunnier than Miami and one of the sunniest large cities in the US.",
    },
    {
        "question": "Which Sacramento band is known for alternative metal hits like 'Change'?",
        "options": ["Tesla", "Cake", "Deftones", "Death Angel"],
        "answer": 2,
        "explanation": "Deftones formed at Del Campo High School in Sacramento in the 1980s and became globally renowned for their unique blend of alternative metal and shoegaze.",
    },
    {
        "question": "What is tule fog?",
        "options": ["A type of Sacramento beer", "A dense ground fog in the Central Valley", "A local weather festival", "A Sacramento neighborhood"],
        "answer": 1,
        "explanation": "Tule fog is a dense ground fog that forms in the Sacramento Valley in winter. It can reduce visibility to near zero and is the leading cause of weather-related accidents in California.",
    },
    {
        "question": "When was Old Sacramento designated a National Historic Landmark?",
        "options": ["1938", "1965", "1979", "1991"],
        "answer": 1,
        "explanation": "Old Sacramento was designated a National Historic Landmark in 1965, preserving 28 acres of Gold Rush-era buildings along the Sacramento River waterfront.",
    },
    {
        "question": "What year did Sacramento Republic FC set a USL attendance world record?",
        "options": ["2012", "2014", "2016", "2018"],
        "answer": 1,
        "explanation": "In 2014, Sacramento Republic FC drew over 11,000 fans to their USL home opener — a world record for the league at the time.",
    },
    {
        "question": "How many counties does UC Davis Medical Center serve as a trauma center?",
        "options": ["15", "22", "33", "40"],
        "answer": 2,
        "explanation": "UC Davis Medical Center is the only Level 1 trauma center serving a 33-county area in Northern California and Nevada.",
    },
]
